const ELEMENT_IDS = {
    TRIGGER_MESSAGE_BUTTON: 'trigger-show-message-button',
    GET_SERIAL_PORTS_BUTTON: 'get-serial-ports-button',
    FLASH_SERIAL_PORTS_BUTTON: 'flash-serial-ports-button',
};

const ELEMENT_NAMES = {
    SERIAL_PORT_OPTION_INPUT: 'serial-port-option-input',
}

const POST_MESSAGE_ACTION = {
    SHOW_WARNING_LOG: 'SHOW_WARNING_LOG',
    OPEN_NEW_TERMINAL: 'OPEN_NEW_TERMINAL',
    GET_SERIAL_PORT_LIST: 'GET_SERIAL_PORT_LIST',
    FLASH_SERIAL_PORT_LIST: 'FLASH_SERIAL_PORT_LIST',
    ADD_PORT_TO_FLASH_LIST: 'ADD_PORT_TO_FLASH_LIST',
    REMOVE_PORT_FROM_FLASH_LIST: 'REMOVE_PORT_FROM_FLASH_LIST'
}