const ELEMENT_IDS = {
    TRIGGER_MESSAGE_BUTTON: 'trigger-show-message-button',
    GET_SERIAL_PORTS_BUTTON: 'get-serial-ports-button',
};

const POST_MESSAGE_ACTION = {
    SHOW_WARNING_LOG: 'SHOW_WARNING_LOG',
    OPEN_NEW_TERMINAL: 'OPEN_NEW_TERMINAL',
    GET_SERIAL_PORT_LIST: 'GET_SERIAL_PORT_LIST'
}